name: Release Radar Request
description: Form to request your project be included in the GitHub Release Radar
title: "[Release Radar Request] <title>"
assignees: MishManners
body:
- type: input
  attributes:
    label: Open Source Project name
    description: What is the name of your open source project?
    placeholder: ex. GitHub CLI
  validations:
    required: true
- type: textarea
  attributes:
    label: Content or Product Stakeholder(s)
    description: Who can we follow up with for a review?
    placeholder: ex. @handle
  validations:
    required: true
- type: dropdown
  attributes:
    label: Platform
    description: Where should this video be posted? (You can choose multiple platforms, if needed)
    multiple: true
    options:
      - Youtube
      - Linkedin
      - Twitter
      - TikTok
      - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: Audience
    description: Who is the intended audience?
  validations:
    required: true
- type: textarea
  attributes:
    label: Business Value
    description: How will this drive business goals?
  validations:
    required: true
- type: textarea
  attributes:
    label: More Information
    description: If you would like to add any more information, please add it below
    placeholder: You rock!
  validations:
    required: false

