name: Release Radar Request
description: Form to request your project be included in the GitHub Release Radar
title: "[Release Radar Request] <title>"
assignees: MishManners
body:
- type: input
  attributes:
    label: Open Source Project name
    description: What is the name of your open source project?
    placeholder: ex. GitHub CLI
  validations:
    required: true
- type: textarea
  attributes:
    label: What is your project?
    description: 1-2 sentences about what your open source project is/does.
    placeholder: ex. The GitHub CLI is GitHub on the command line. It brings pull requests, issues, and other GitHub concepts to the terminal next to where you are already working with git and your code.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Version
    description: The Release Radar covers major version releases. What release is your project shipping?
    multiple: true
    options:
      - 1.0
      - 2.0 
      - 3.0
      - 4.0
      - 5.0
      - 6.0
      - 7.0
      - 8.0
      - 9.0
      - 10.0
      - Other (please fill out below)
  validations:
    required: true
- type: input
  attributes:
    label: version-higher
    description: Have you shipped a version higher than 10.0? Please write the version number below.
    placeholder: ex. 27.0
  validations:
    required: false
- type: textarea
  attributes:
    label: Business Value
    description: How will this drive business goals?
  validations:
    required: true
- type: textarea
  attributes:
    label: More Information
    description: If you would like to add any more information, please add it below
    placeholder: You rock!
  validations:
    required: false

