name: Release Radar Request
description: Form to request your project be included in the GitHub Release Radar
title: "[RR Request]: <Name and version of your open source project>"
assignees: MishManners
body:
- type: input
  attributes:
    label: Open Source Project name
    description: What is the name of your open source project?
    placeholder: ex. GitHub CLI
  validations:
    required: true
- type: textarea
  attributes:
    label: What is your project?
    description: 1-2 sentences about what your open source project is/does.
    placeholder: ex. The GitHub CLI is GitHub on the command line. It brings pull requests, issues, and other GitHub concepts to the terminal next to where you are already working with git and your code.
  validations:
    required: true
- type: input
  attributes:
    label: Version
    description: The Release Radar covers major version releases. What version number is your project shipping? Note, if you use a different release convention other than semantic version by number (x.0), please note that below so we can still consider you for the Release Radar. 
    placeholder: ex. 2.0
  validations:
    required: true
- type: input
  attributes:
    label: Date
    description: What date did you ship this release?
    placeholder: ex. August 25, 2021
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of breaking changes
    description: 2-3 sentences on the major changes you have shipped with your latest update. If you have only shipped version 1.0, feel free to write nil.
    placeholder: ex. The latest changes includes support for Codespaces, and the ability to delete repos. There are also more extensions available.
  validations:
    required: true
- type: input
  attributes:
    label: GitHub Repo
    description: Please post a link to your GitHub repository.
    placeholder: ex. https://github.com/cli/cli/
  validations:
    required: true
- type: input
  attributes:
    label: Website
    description: Please post a link to your website.
    placeholder: ex. https://cli.github.com/
  validations:
    required: true
- type: input
  attributes:
    label: Link to changelog
    description: Please post a link to your release notes, blog post, or similar.
    placeholder: ex. https://github.com/cli/cli/releases/tag/v2.2.0
  validations:
    required: true
- type: input
  attributes:
    label: Social media
    description: Did you post about your release on social media? Paste a link here.
    placeholder: ex. https://twitter.com/github/status/1430204045801758725
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else to add?
    description: If you would like to add any more information, please add it below. If your software uses a different versioning system other than version by number (ie. 1.0, 2.0 etc.), please let us know here (ie. version by name, version by date). 
    placeholder: You rock!
  validations:
    required: false

